### ISSUE TITLE
Include config files from a directory

### ISSUE THREAD

**Issue by santiagorr** [subgraph/paxrat#20] opened 2017-01-17 16:22 UTC
Hi,

Please, consider making it possible for paxrat to read config files from a directory (such as /etc/paxrat.conf.d/). This would allow users to have custom configs, and ease maintaining a base paxrat.conf among distributions.

The directory path(s) could be set by a "include" stanza in /etc/paxrat.conf. 

What do you think?

Cheers,

  -- Santiago

**Comment by xSmurf** [comment] 2017-01-17 17:47
This is definitely something I'd like to get done (sort of duplicate of #18).

For now you can use the `-c` flag to call a custom file.

**Comment by mckinney-subgraph** [comment] 2017-04-09 13:53
This has been implemented:
[https://github.com/subgraph/paxrat/commit/843dd41e4e1aa7a0487423d91fc8404f715ac916](https://github.com/subgraph/paxrat/commit/843dd41e4e1aa7a0487423d91fc8404f715ac916)

When running paxrat with no config file argument or the default path, PaX flag config files found in `/etc/paxrat/conf.d/` will be applied. Running with no args is the preferred mode of execution. Running with a specific config path is better used for *watcher* mode, for example: what we do with `torbrowser-launcher`.

**Closed as completed by mckinney-subgraph** 2017-04-09 13:53 UTC

**Comment by santiagorr** [comment] 2017-04-10 11:24
El 09/04/17 a las 06:53, mckinney-subgraph escribió:
>    This has been implemented:
>    [1]843dd41
> 
…

\O/ Great, thank you!
